// GENERATED by tools/stamp_build.py — do not edit by hand.
//
// The build marker shown at the foot of About Speechcraft. It exists so a
// stale cache is visible instead of inferred: this file ships with the
// code it describes, so an old build carries an old date and cannot claim
// to be newer than it is.
//
// Re-stamp before committing changes under js/ or css/. launch_lint fails
// if this falls behind the newest commit that touched either.
export const BUILD = Object.freeze({
  date: '2026-10-04',
  commit: '865854b',
});
