#!/usr/bin/env python3
"""Generate privacy.html and terms.html from the pages the app already shows.

WHY THIS EXISTS (2026-10-03, terms added 2026-10-05). Both app stores
require a privacy policy at a PUBLIC URL, and both want terms alongside it.
Speechcraft has had a good policy since 22 September 2026 and terms of the
same date, but routing here is function-based rather than URL-based, so
there was no link that opened either one: they existed and could not be
linked to.

NEITHER DOCUMENT IS COPIED. The ones inside js/main.js, on the Privacy &
Data and Terms of Use pages, stay the single source of truth, and this tool
lifts them into standalone pages. Writing the words twice is how two
privacy policies end up disagreeing about what an app stores, which is a
worse problem than not having a URL. launch_lint re-runs this generator and
fails if either page has drifted from it, so they cannot part company
unnoticed.

The two pages are lifted differently because they are written differently.
The policy is a plain <section> that can be moved verbatim. The terms are
built from a sec() helper inside a template literal, so the helper is
expanded here — and its exact definition is pinned, so that changing it in
js/main.js fails this generator loudly instead of quietly producing markup
that no longer matches the app.

The generated pages carry NO JavaScript, so they render for a store
reviewer, a crawler or anyone with scripting off. The CSP is read out of
index.html rather than written out again here, for the same reason.

    python3 tools/build_legal.py            # write both pages
    python3 tools/build_legal.py --check    # exit 1 if either has drifted
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAIN = os.path.join(ROOT, 'js', 'main.js')
INDEX = os.path.join(ROOT, 'index.html')

PAGE = '''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <!-- GENERATED by tools/build_legal.py from %(source)s in js/main.js.
       Do not edit by hand: launch_lint fails if this drifts from it. -->
  <meta http-equiv="Content-Security-Policy" content="%(csp)s" />
  <meta name="referrer" content="no-referrer" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>%(title)s</title>
  <link rel="icon" href="favicon.svg" type="image/svg+xml" />
  <link rel="stylesheet" href="css/style.css" />
</head>
<body>
  <main class="guide">
    <h1>%(heading)s</h1>
%(intro)s
%(body)s
    <p class="pane-note">Questions go through the Feedback page in the app,
      which opens the project&rsquo;s GitHub Issues.</p>
    <p class="pane-note"><a href="./">Back to Speechcraft</a></p>
  </main>
</body>
</html>
'''

PRIVACY_INTRO = '''    <p class="guide-text">Speechcraft is a speech, acting and dialect trainer.
      It has no accounts and no servers of its own. This is the same policy
      shown inside the app under <b>More &rarr; Privacy &amp; Data</b>, where
      you can also see everything stored on your device and delete it.</p>'''

TERMS_INTRO = '''    <p class="guide-text">Speechcraft is a speech, acting and dialect trainer.
      It is free, it has no accounts and it sells nothing. These are the same
      terms shown inside the app under <b>More &rarr; Terms of Use</b>.</p>'''

# The sec() helper from renderTerms, expanded by hand in _expand_sec below.
# Pinned verbatim: if the helper changes shape, this generator must stop
# rather than keep emitting the markup the old one produced.
SEC_DEF = ("const sec = (h, ...ps) => `<h2 class=\"guide-heading\">${h}</h2>"
           "${ps.map(p => `<p class=\"guide-text\">${p}</p>`).join('')}`;")


def extract_policy(src):
    """The #privacy-policy <section> from main.js, verbatim.

    Anchored on the id and closed by the first </section> after it. The
    section contains no template interpolation — checked below, because a
    ${...} lifted into a static page would ship as literal text.
    """
    anchor = src.find('<section class="stat-block" id="privacy-policy">')
    if anchor == -1:
        return None, 'the #privacy-policy section is gone from js/main.js'
    end = src.find('</section>', anchor)
    if end == -1:
        return None, 'the #privacy-policy section is never closed'
    # Start at the beginning of that LINE, so the block carries its own
    # indentation and can be dedented as a whole.
    start = src.rfind('\n', 0, anchor) + 1
    block = src[start:end + len('</section>')]
    if '${' in block:
        return None, 'the policy section gained a ${...} expression, which cannot be made static'
    return _reindent(block.split('\n')), None


def _reindent(lines):
    """Dedent a lifted block to zero, then indent it to sit inside <main>."""
    widths = [len(ln) - len(ln.lstrip()) for ln in lines if ln.strip()]
    cut = min(widths) if widths else 0
    out = [('    ' + ln[cut:]).rstrip() if ln.strip() else '' for ln in lines]
    return '\n'.join(out)


def _match_paren(s, k):
    """Index of the ')' closing the '(' at s[k], skipping string literals."""
    depth = 0
    instr = False
    i = k
    while i < len(s):
        c = s[i]
        if instr:
            if c == '\\':
                i += 2
                continue
            if c == "'":
                instr = False
        elif c == "'":
            instr = True
        elif c == '(':
            depth += 1
        elif c == ')':
            depth -= 1
            if depth == 0:
                return i, None
        i += 1
    return None, 'an unclosed sec( ... ) call in renderTerms'


def _js_strings(argsrc):
    """Parse sec()'s arguments: a comma-separated list of quoted strings.

    Deliberately narrow. The terms are written with curly quotation marks
    and apostrophes, so a straight quote inside one of these strings means
    the house style has slipped, and an expression where a literal belongs
    means this parser is the wrong tool — both stop the build rather than
    guess.
    """
    out = []
    i = 0
    n = len(argsrc)
    while i < n:
        ch = argsrc[i]
        if ch in ' \t\r\n,':
            i += 1
            continue
        if ch != "'":
            return None, ('sec() takes quoted strings; found %r'
                          % argsrc[i:i + 40])
        i += 1
        buf = []
        closed = False
        while i < n:
            c = argsrc[i]
            if c == '\\':
                if i + 1 >= n:
                    return None, 'a sec() string ends in a backslash'
                nxt = argsrc[i + 1]
                if nxt in ("'", '\\'):
                    buf.append(nxt)
                    i += 2
                    continue
                return None, ('a sec() string uses the escape \\%s, which '
                              'this generator does not handle' % nxt)
            if c == "'":
                i += 1
                closed = True
                break
            buf.append(c)
            i += 1
        if not closed:
            return None, 'an unterminated string in a sec() call'
        out.append(''.join(buf))
    return out, None


def _expand_sec(block):
    """Replace every ${sec('heading', 'para', ...)} with the HTML it builds."""
    marker = '${sec('
    out = []
    i = 0
    while True:
        j = block.find(marker, i)
        if j == -1:
            out.append(block[i:])
            return ''.join(out), None
        line_start = block.rfind('\n', 0, j) + 1
        indent = block[line_start:j]
        if indent.strip():
            return None, 'a ${sec(...)} call does not begin its own line'
        out.append(block[i:line_start])
        open_paren = j + len(marker) - 1
        close, err = _match_paren(block, open_paren)
        if err:
            return None, err
        if not block.startswith('}', close + 1):
            return None, 'a ${sec(...)} call is not closed by a brace'
        args, err = _js_strings(block[open_paren + 1:close])
        if err:
            return None, err
        if len(args) < 2:
            return None, 'a sec() call has a heading but no paragraph'
        parts = ['%s<h2 class="guide-heading">%s</h2>' % (indent, args[0])]
        for para in args[1:]:
            parts.append('%s<p class="guide-text">%s</p>' % (indent, para))
        out.append('\n'.join(parts))
        i = close + 2


def extract_terms(src):
    """The body of renderTerms, with its sec() helper expanded.

    The <h1> and the Feedback button are dropped: the page supplies its own
    heading, and a button that calls renderFeedback cannot work on a page
    with no JavaScript. The note above the Back link covers it instead.
    """
    anchor = src.find('function renderTerms() {')
    if anchor == -1:
        return None, 'renderTerms is gone from js/main.js'
    if SEC_DEF not in src[anchor:anchor + 800]:
        return None, ('the sec() helper in renderTerms has changed shape, so '
                      'this generator can no longer expand it')
    start = src.find('<main class="guide">', anchor)
    if start == -1:
        return None, 'renderTerms no longer opens a <main class="guide">'
    start += len('<main class="guide">')
    end = src.find('</main>', start)
    if end == -1:
        return None, 'renderTerms never closes its <main>'
    expanded, err = _expand_sec(src[start:end])
    if err:
        return None, err
    lines = [ln for ln in expanded.split('\n')
             if '<button' not in ln and '<h1>' not in ln]
    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()
    if not lines:
        return None, 'renderTerms produced no terms'
    if '${' in '\n'.join(lines):
        return None, ('the terms page gained a ${...} expression that cannot '
                      'be made static')
    return _reindent(lines), None


def render():
    """Both pages, keyed by the filename each one belongs in."""
    with open(MAIN, 'r', encoding='utf-8') as fh:
        main_src = fh.read()
    with open(INDEX, 'r', encoding='utf-8') as fh:
        index_src = fh.read()
    m = re.search(r'Content-Security-Policy" content="([^"]+)"', index_src)
    if not m:
        return None, 'no CSP found in index.html'
    csp = m.group(1)

    policy, err = extract_policy(main_src)
    if err:
        return None, err
    terms, err = extract_terms(main_src)
    if err:
        return None, err

    return {
        'privacy.html': PAGE % {
            'source': 'the policy', 'csp': csp,
            'title': 'Privacy Policy — Speechcraft',
            'heading': 'Speechcraft — Privacy Policy',
            'intro': PRIVACY_INTRO, 'body': policy,
        },
        'terms.html': PAGE % {
            'source': 'the terms', 'csp': csp,
            'title': 'Terms of Use — Speechcraft',
            'heading': 'Speechcraft — Terms of Use',
            'intro': TERMS_INTRO, 'body': terms,
        },
    }, None


def main():
    pages, err = render()
    if err:
        print('build_legal: FAILED — ' + err)
        return 1
    check = '--check' in sys.argv
    drifted = []
    for name in sorted(pages):
        path = os.path.join(ROOT, name)
        have = None
        if os.path.exists(path):
            with open(path, 'r', encoding='utf-8') as fh:
                have = fh.read()
        if check:
            if have != pages[name]:
                drifted.append(name)
            continue
        if have != pages[name]:
            with open(path, 'w', encoding='utf-8') as fh:
                fh.write(pages[name])
            print('build_legal: %s written' % name)
        else:
            print('build_legal: %s unchanged' % name)
    if check:
        if drifted:
            print('build_legal: %s has DRIFTED — run python3 tools/build_legal.py'
                  % ' and '.join(drifted))
            return 1
        print('build_legal: privacy.html and terms.html are in sync with js/main.js')
    return 0


if __name__ == '__main__':
    sys.exit(main())
