#!/usr/bin/env python3
"""Generate privacy.html from the policy the app already shows.

WHY THIS EXISTS (2026-10-03). Both app stores require a privacy policy at
a PUBLIC URL. Speechcraft has had a good policy since 22 September 2026,
but routing here is function-based rather than URL-based, so there was no
link that opened it: the policy existed and could not be linked to.

THE POLICY IS NOT COPIED. The one inside js/main.js, on the Privacy &
Data page, stays the single source of truth, and this tool lifts that
exact section into a standalone page. Writing the words twice is how two
privacy policies end up disagreeing about what an app stores, which is a
worse problem than not having a URL. launch_lint re-runs this generator
and fails if privacy.html has drifted from it, so the two cannot part
company unnoticed.

The generated page carries NO JavaScript, so it renders for a store
reviewer, a crawler or anyone with scripting off. The CSP is read out of
index.html rather than written out again here, for the same reason.

    python3 tools/build_legal.py            # write privacy.html
    python3 tools/build_legal.py --check    # exit 1 if it has drifted
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAIN = os.path.join(ROOT, 'js', 'main.js')
INDEX = os.path.join(ROOT, 'index.html')
OUT = os.path.join(ROOT, 'privacy.html')

PAGE = '''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <!-- GENERATED by tools/build_legal.py from the policy in js/main.js.
       Do not edit by hand: launch_lint fails if this drifts from it. -->
  <meta http-equiv="Content-Security-Policy" content="%(csp)s" />
  <meta name="referrer" content="no-referrer" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Privacy Policy — Speechcraft</title>
  <link rel="icon" href="favicon.svg" type="image/svg+xml" />
  <link rel="stylesheet" href="css/style.css" />
</head>
<body>
  <main class="guide">
    <h1>Speechcraft — Privacy Policy</h1>
    <p class="guide-text">Speechcraft is a speech, acting and dialect trainer.
      It has no accounts and no servers of its own. This is the same policy
      shown inside the app under <b>More &rarr; Privacy &amp; Data</b>, where
      you can also see everything stored on your device and delete it.</p>
%(policy)s
    <p class="pane-note">Questions go through the Feedback page in the app,
      which opens the project&rsquo;s GitHub Issues.</p>
    <p class="pane-note"><a href="./">Back to Speechcraft</a></p>
  </main>
</body>
</html>
'''


def extract_policy(src):
    """The #privacy-policy <section> from main.js, verbatim.

    Anchored on the id and closed by the first </section> after it. The
    section contains no template interpolation — checked below, because a
    ${...} lifted into a static page would ship as literal text.
    """
    anchor = src.find('<section class="stat-block" id="privacy-policy">')
    if anchor == -1:
        return None, 'the #privacy-policy section is gone from js/main.js'
    end = src.find('</section>', anchor)
    if end == -1:
        return None, 'the #privacy-policy section is never closed'
    # Start at the beginning of that LINE, so the block carries its own
    # indentation and can be dedented as a whole.
    start = src.rfind('\n', 0, anchor) + 1
    block = src[start:end + len('</section>')]
    if '${' in block:
        return None, 'the policy section gained a ${...} expression, which cannot be made static'
    # The policy sits deep inside a template literal. Dedent to zero, then
    # re-indent to sit inside <main> on the generated page.
    lines = block.split('\n')
    widths = [len(ln) - len(ln.lstrip()) for ln in lines if ln.strip()]
    cut = min(widths) if widths else 0
    out = [('    ' + ln[cut:]).rstrip() if ln.strip() else '' for ln in lines]
    return '\n'.join(out), None


def render():
    with open(MAIN, 'r', encoding='utf-8') as fh:
        main_src = fh.read()
    with open(INDEX, 'r', encoding='utf-8') as fh:
        index_src = fh.read()
    policy, err = extract_policy(main_src)
    if err:
        return None, err
    m = re.search(r'Content-Security-Policy" content="([^"]+)"', index_src)
    if not m:
        return None, 'no CSP found in index.html'
    return PAGE % {'csp': m.group(1), 'policy': policy}, None


def main():
    want, err = render()
    if err:
        print('build_legal: FAILED — ' + err)
        return 1
    check = '--check' in sys.argv
    have = None
    if os.path.exists(OUT):
        with open(OUT, 'r', encoding='utf-8') as fh:
            have = fh.read()
    if check:
        if have == want:
            print('build_legal: privacy.html is in sync with js/main.js')
            return 0
        print('build_legal: privacy.html has DRIFTED — run python3 tools/build_legal.py')
        return 1
    with open(OUT, 'w', encoding='utf-8') as fh:
        fh.write(want)
    print('build_legal: privacy.html %s' % ('unchanged' if have == want else 'written'))
    return 0


if __name__ == '__main__':
    sys.exit(main())
