#!/usr/bin/env python3
"""Generate js/data/audio-coverage.js from the actual audio tree.

Long-form (per-line) recordings are only claimed where a text's COMPLETE
line set exists on disk for a dialect — partial coverage is never shown as
a working voice. Also emits docs/LONGFORM_RECORDING_MANIFEST.md listing
everything still missing (the no-spend batch plan).

Zero-dependency, Python 3.9. Run after any audio generation:
    python3 tools/longform_coverage.py
"""

import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
AUDIO = ROOT / "audio"
DATA = ROOT / "js" / "data"

DIALECTS = ["nam", "rp", "aus", "ssbe"]
LIBS = ["chekhov", "oneill", "wilde", "pirandello", "ibsen"]


def sonnet_line_counts():
    src = (DATA / "sonnets.js").read_text(encoding="utf-8")
    counts = {}
    # entries like { n: 18, lines: ['...', '...'] }
    for m in re.finditer(r"n:\s*(\d+),\s*lines:\s*\[(.*?)\]", src, re.S):
        n = int(m.group(1))
        counts[n] = len(re.findall(r'"(?:[^"\\]|\\.)*"', m.group(2)))
    return counts


def lib_line_counts(lib):
    p = DATA / (lib + ".js")
    if not p.exists():
        return {}
    src = p.read_text(encoding="utf-8")
    counts = {}
    for m in re.finditer(r'id:\s*["\']([^"\']+)["\'](.*?)lines:\s*\[(.*?)\]', src, re.S):
        counts[m.group(1)] = len(re.findall(r'"(?:[^"\\]|\\.)*"|(?<!\\)\'(?:[^\'\\]|\\.)*\'', m.group(3)))
    return counts


def clips_by_text(folder, key_type=int):
    """{text id: line count on disk} from files named <id>-<line>.mp3."""
    out = {}
    if not folder.is_dir():
        return out
    for f in folder.glob("*.mp3"):
        m = re.match(r"(.+)-(\d+)$", f.stem)
        if not m:
            continue
        try:
            key = key_type(m.group(1))
        except ValueError:
            key = m.group(1)
        out[key] = out.get(key, 0) + 1
    return out


def main():
    coverage = {"sonnets": {}, "libs": {}}
    missing_lines = []

    expected = sonnet_line_counts()
    for d in DIALECTS:
        have = clips_by_text(AUDIO / "sonnets" / d)
        complete = sorted(n for n, want in expected.items() if want > 0 and have.get(n, 0) >= want)
        coverage["sonnets"][d] = complete
        gap = [n for n in expected if n not in complete]
        if gap:
            lines = sum(expected[n] - min(have.get(n, 0), expected[n]) for n in gap)
            missing_lines.append((f"sonnets/{d}", len(gap), lines))

    for lib in LIBS:
        expected_l = lib_line_counts(lib)
        coverage["libs"][lib] = {}
        for d in DIALECTS:
            have = clips_by_text(AUDIO / lib / d, key_type=str)
            complete = sorted(i for i, want in expected_l.items() if want > 0 and have.get(i, 0) >= want)
            coverage["libs"][lib][d] = complete
            gap = [i for i in expected_l if i not in complete]
            if gap:
                lines = sum(expected_l[i] - min(have.get(i, 0), expected_l[i]) for i in gap)
                missing_lines.append((f"{lib}/{d}", len(gap), lines))

    out = (
        "// GENERATED by tools/longform_coverage.py — do not edit by hand.\n"
        "// A dialect is listed for a text ONLY when its complete line set\n"
        "// exists on disk. This is the single truth source for which voices\n"
        "// the Texts & Speeches reader may present as recorded.\n"
        "export const LONGFORM_COVERAGE = " + json.dumps(coverage, indent=1) + ";\n"
    )
    (DATA / "audio-coverage.js").write_text(out, encoding="utf-8")

    doc = ["# Long-form recording manifest (generated)", "",
           "Missing full-text recordings, by collection and dialect.",
           "Generated by `tools/longform_coverage.py`. No audio is produced",
           "by this script — it is the batch plan for future generation.", "",
           "| Collection/dialect | Texts incomplete | Lines to record |",
           "| --- | --- | --- |"]
    for name, texts, lines in sorted(missing_lines):
        doc.append(f"| {name} | {texts} | {lines} |")
    if not missing_lines:
        doc.append("| — | 0 | 0 |")
    (ROOT / "docs" / "LONGFORM_RECORDING_MANIFEST.md").write_text("\n".join(doc) + "\n", encoding="utf-8")

    print("sonnets fully covered:", {d: len(v) for d, v in coverage["sonnets"].items()})
    print("library texts fully covered:", {l: {d: len(v) for d, v in ds.items() if v} for l, ds in coverage["libs"].items()})
    print("manifest rows:", len(missing_lines))


if __name__ == "__main__":
    main()
