#!/usr/bin/env python3
"""Stamp js/build.js with the current commit date and short hash.

WHY THIS EXISTS (2026-10-02). There was no way to tell from inside the app
which build you were looking at. The owner opened the live site, saw three
workspaces instead of six, and reported it as a missing deploy; it was
actually a service worker serving JavaScript from before 23 September,
which stale-while-revalidate repaired on the next load. Diagnosing that
took reading the deployed source and inferring the build from WHICH
workspaces were absent. A visible stamp answers it in one glance.

The stamp SHIPS WITH THE CODE IT DESCRIBES, which is the whole point: an
old cached build carries its own old stamp, so it cannot overstate how
fresh it is. The only way it can be wrong is by being BEHIND, if somebody
edits the app and forgets to re-stamp — a false alarm, never a false pass.
launch_lint fails on exactly that, so it cannot go stale unnoticed.

Run it before committing anything under js/ or css/:

    python3 tools/stamp_build.py

It names the commit it was stamped AT, which is the commit before the one
carrying the stamp. That is honest and it is what you want: it says what
code this build was cut from.
"""
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'js', 'build.js')

TEMPLATE = '''// GENERATED by tools/stamp_build.py — do not edit by hand.
//
// The build marker shown at the foot of About Speechcraft. It exists so a
// stale cache is visible instead of inferred: this file ships with the
// code it describes, so an old build carries an old date and cannot claim
// to be newer than it is.
//
// Re-stamp before committing changes under js/ or css/. launch_lint fails
// if this falls behind the newest commit that touched either.
export const BUILD = Object.freeze({
  date: '%(date)s',
  commit: '%(commit)s',
});
'''


def git(*args):
    """Run a git command in the repo, or return None if git cannot answer."""
    try:
        out = subprocess.run(
            ['git'] + list(args), cwd=ROOT,
            stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, check=True)
        return out.stdout.decode('utf-8', 'replace').strip()
    except (OSError, subprocess.CalledProcessError):
        return None


def current_stamp():
    """The {date, commit} recorded in js/build.js, or None."""
    try:
        with open(OUT, 'r', encoding='utf-8') as fh:
            src = fh.read()
    except IOError:
        return None
    date = re.search(r"date:\s*'([^']*)'", src)
    commit = re.search(r"commit:\s*'([^']*)'", src)
    if not date or not commit:
        return None
    return {'date': date.group(1), 'commit': commit.group(1)}


def main():
    date = git('log', '-1', '--date=short', '--format=%cd')
    commit = git('log', '-1', '--format=%h')
    if not date or not commit:
        print('stamp_build: git is not available here; js/build.js left alone.')
        return 0
    before = current_stamp()
    with open(OUT, 'w', encoding='utf-8') as fh:
        fh.write(TEMPLATE % {'date': date, 'commit': commit})
    if before and before['date'] == date and before['commit'] == commit:
        print('stamp_build: unchanged (%s / %s)' % (date, commit))
    else:
        was = '%s / %s' % (before['date'], before['commit']) if before else 'nothing'
        print('stamp_build: %s -> %s / %s' % (was, date, commit))
    return 0


if __name__ == '__main__':
    sys.exit(main())
